name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          export PATH=$HOME/.local/share/pnpm/global/5/node_modules/.bin:$PATH

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run CI tasks with pnpm
        run: pnpm run ci
